# Generated by Django 4.0.3 on 2022-04-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaEutaQuestionHo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_haru', models.CharField(max_length=200)),
                ('question_num', models.IntegerField()),
            ],
        ),
    ]
