# Generated by Django 4.0.3 on 2022-04-22 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaAnsewersHo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_haru', models.CharField(max_length=100)),
                ('answer_number', models.IntegerField()),
                ('right_ans', models.BooleanField()),
                ('belongs_to', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mocks.maeutaquestionho')),
            ],
        ),
    ]
