# Generated by Django 4.0.3 on 2022-05-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocks', '0002_maansewersho'),
    ]

    operations = [
        migrations.CreateModel(
            name='SabKoScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_haru', models.IntegerField()),
            ],
        ),
    ]
